//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 39, 48")]
        public global::System.Drawing.Color PrimaryColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimaryColor"]));
            }
            set {
                this["PrimaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 97, 152")]
        public global::System.Drawing.Color SecondaryColor {
            get {
                return ((global::System.Drawing.Color)(this["SecondaryColor"]));
            }
            set {
                this["SecondaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BgColor {
            get {
                return ((global::System.Drawing.Color)(this["BgColor"]));
            }
            set {
                this["BgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AverageDataId, ScriptId, ScriptName, DateTime, Open, High, Low, Average, Close, R" +
            "ecordId, DateTimeSlot")]
        public string AverageColumns {
            get {
                return ((string)(this["AverageColumns"]));
            }
            set {
                this["AverageColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("id,RecordId,ScriptId,DateTimeSlot,DateTime,Open,High,Low,Close,SMA,StandardDeviat" +
            "ion,Deviations,LowerBand,UpperBand,ScriptName")]
        public string BollingerColumns {
            get {
                return ((string)(this["BollingerColumns"]));
            }
            set {
                this["BollingerColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MACDDataId,ScriptId,RecordId,ScriptName,DateTimeSlot,DateTime,Open,High,Low,Close" +
            ",EMA1,EMA2,MACD,Signal,Percentage,Histogram,TragetGen,BuySellPrice")]
        public string MACDCloumns {
            get {
                return ((string)(this["MACDCloumns"]));
            }
            set {
                this["MACDCloumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RSIDataId,ScriptId,ScriptName,DateTimeSlot,DateTime,Open,High,Low,Close,RecordId," +
            "Change,Advance,Decline,AvgGain_Slow,AvgLoss_Slow,RS_Slow,RSI_Slow,AvgGain_Fast,A" +
            "vgLoss_Fast,RS_Fast,RSI_Fast,TargetGenFast,BuySellPriceFast,TargetFast")]
        public string RSIColumns {
            get {
                return ((string)(this["RSIColumns"]));
            }
            set {
                this["RSIColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SwingDataId,ScriptId,ScriptName,DateTimeSlot,DateTime,Open,High,Low,Close,SwingIn" +
            "dex,ATR,ATRAvg,UpperBand,LowerBand,AvgLowerBand,AvgUpperBand,DiffUp,DiffLow,Call" +
            ",RecordId")]
        public string SwingColumns {
            get {
                return ((string)(this["SwingColumns"]));
            }
            set {
                this["SwingColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StochasticColumns {
            get {
                return ((string)(this["StochasticColumns"]));
            }
            set {
                this["StochasticColumns"] = value;
            }
        }
    }
}
