//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_ScriptPortfolio
    {
        public int ScriptPortID { get; set; }
        public Nullable<int> ScriptID { get; set; }
        public Nullable<int> PortfolioID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
    }
}
