//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_EODData
    {
        public int ID { get; set; }
        public int Company { get; set; }
        public Nullable<decimal> OPEN { get; set; }
        public Nullable<decimal> HIGH { get; set; }
        public Nullable<decimal> LOW { get; set; }
        public Nullable<decimal> CLOSE { get; set; }
        public Nullable<decimal> LAST { get; set; }
        public Nullable<decimal> TOTTRDQTY { get; set; }
        public Nullable<decimal> TOTTRDVAL { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<decimal> TOTALTRADES { get; set; }
    }
}
