//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_UserDefineFormula
    {
        public int FormulaID { get; set; }
        public string Formula { get; set; }
        public bool IsActive { get; set; }
        public int IDUser { get; set; }
        public string FormulaName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
