//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_SwingParameters
    {
        public int ID { get; set; }
        public Nullable<int> SwingID { get; set; }
        public Nullable<double> LimitMove { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public Nullable<int> SwingBandTimePeriod { get; set; }
    }
}
