//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_Pivote
    {
        public int PivoteID { get; set; }
        public int Company { get; set; }
        public System.DateTime Datefor { get; set; }
        public Nullable<System.DateTime> CalculatedDatetime { get; set; }
        public Nullable<decimal> OpenReadings { get; set; }
        public Nullable<decimal> HighReadings { get; set; }
        public Nullable<decimal> LowReadings { get; set; }
        public Nullable<decimal> CloseReadings { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Pivotpoint { get; set; }
        public Nullable<decimal> R1 { get; set; }
        public Nullable<decimal> R_Mid_1 { get; set; }
        public Nullable<decimal> R2 { get; set; }
        public Nullable<decimal> R_Mid_2 { get; set; }
        public Nullable<decimal> R3 { get; set; }
        public Nullable<decimal> R_Mid_3 { get; set; }
        public Nullable<decimal> R4 { get; set; }
        public Nullable<decimal> R_Mid_4 { get; set; }
        public Nullable<decimal> S1 { get; set; }
        public Nullable<decimal> S_Mid_1 { get; set; }
        public Nullable<decimal> S2 { get; set; }
        public Nullable<decimal> S_Mid_2 { get; set; }
        public Nullable<decimal> S3 { get; set; }
        public Nullable<decimal> S_Mid_3 { get; set; }
        public Nullable<decimal> S4 { get; set; }
        public Nullable<decimal> S_Mid_4 { get; set; }
    
        public virtual Tbl_ScriptMaster Tbl_ScriptMaster { get; set; }
    }
}
