//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_SplitMergeHistory
    {
        public int ID { get; set; }
        public int ScriptID { get; set; }
        public int SplitMergeType { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<int> ReplacedScriptID { get; set; }
        public string SplitValue { get; set; }
        public Nullable<System.DateTime> SplitBeforeDate { get; set; }
    }
}
