//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_AverageParameters
    {
        public int ID { get; set; }
        public Nullable<int> AverageID { get; set; }
        public Nullable<double> Period { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsExposional { get; set; }
    }
}
