//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_FormulaPortfolio
    {
        public int FormulaPortID { get; set; }
        public string FormulaName { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public string MstName { get; set; }
        public Nullable<int> MstID { get; set; }
        public Nullable<int> PortfolioID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Enterdate { get; set; }
    }
}
