//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_Volatility
    {
        public int VolatilityID { get; set; }
        public string VolatilityName { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MasterID { get; set; }
    }
}
