//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerPoint.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tbl_MACDFilters
    {
        public string BaseLine { get; set; }
        public Nullable<double> PercentageValue { get; set; }
        public int ID { get; set; }
        public Nullable<int> MACDID { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<bool> IsBaseLine { get; set; }
    }
}
